M48
; DRILL file {KiCad (7.0.0-0)} date Tuesday, April 04, 2023 at 11:19:51 PM
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-04-04T23:19:51-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(7.0.0-0)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0669
%
G90
G05
T1
X3.9463Y-3.95
X3.9463Y-4.35
X6.4537Y-3.95
X6.4537Y-4.35
T0
M30
